# Generated by Django 4.0.6 on 2022-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
